export const nseStocks = [
  { symbol: "RELIANCE", name: "Reliance Industries Ltd" },
  { symbol: "TCS", name: "Tata Consultancy Services Ltd" },
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd" },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd" },
  { symbol: "INFY", name: "Infosys Ltd" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Ltd" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd" },
  { symbol: "LT", name: "Larsen & Toubro Ltd" },
  { symbol: "ITC", name: "ITC Ltd" },
  { symbol: "AXISBANK", name: "Axis Bank Ltd" },
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd" },
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Ltd" },
  { symbol: "NTPC", name: "NTPC Ltd" },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India Ltd" },
  { symbol: "TITAN", name: "Titan Company Ltd" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd" },
  { symbol: "NESTLEIND", name: "Nestle India Ltd" },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd" },
  { symbol: "WIPRO", name: "Wipro Ltd" },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd" },
  { symbol: "ADANIPORTS", name: "Adani Ports and Special Economic Zone Ltd" },
  { symbol: "TATASTEEL", name: "Tata Steel Ltd" },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd" },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd" },
  { symbol: "TECHM", name: "Tech Mahindra Ltd" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Ltd" },
  { symbol: "CIPLA", name: "Cipla Ltd" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd" },
  { symbol: "GRASIM", name: "Grasim Industries Ltd" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company Ltd" },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company Ltd" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd" },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd" },
  { symbol: "ONGC", name: "Oil and Natural Gas Corporation Ltd" },
  { symbol: "COALINDIA", name: "Coal India Ltd" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Ltd" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Ltd" },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd" },
  { symbol: "SHREECEM", name: "Shree Cement Ltd" },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd" },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd" },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd" },
  { symbol: "DMART", name: "Avenue Supermarts Ltd" },
  { symbol: "DABUR", name: "Dabur India Ltd" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Ltd" },
  { symbol: "MCDOWELL-N", name: "United Spirits Ltd" },
  { symbol: "SIEMENS", name: "Siemens Ltd" },
  { symbol: "ABB", name: "ABB India Ltd" },
  { symbol: "BOSCHLTD", name: "Bosch Ltd" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd" },
  { symbol: "ACC", name: "ACC Ltd" },
  { symbol: "VEDL", name: "Vedanta Ltd" },
  { symbol: "SAIL", name: "Steel Authority of India Ltd" },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "CANBK", name: "Canara Bank" },
  { symbol: "UNIONBANK", name: "Union Bank of India" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd" },
  { symbol: "FEDERALBNK", name: "The Federal Bank Ltd" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment and Finance Company Ltd" },
  { symbol: "PFC", name: "Power Finance Corporation Ltd" },
  { symbol: "RECLTD", name: "REC Ltd" },
  { symbol: "IRCTC", name: "Indian Railway Catering and Tourism Corporation Ltd" },
  { symbol: "ZOMATO", name: "Zomato Ltd" },
  { symbol: "PAYTM", name: "One 97 Communications Ltd" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures Ltd" },
  { symbol: "NAUKRI", name: "Info Edge (India) Ltd" },
  { symbol: "DELHIVERY", name: "Delhivery Ltd" },
  { symbol: "TRENT", name: "Trent Ltd" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd" },
  { symbol: "ADANIPOWER", name: "Adani Power Ltd" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Ltd" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements Ltd" },
  { symbol: "LUPIN", name: "Lupin Ltd" },
  { symbol: "BIOCON", name: "Biocon Ltd" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Ltd" },
  { symbol: "ALKEM", name: "Alkem Laboratories Ltd" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Ltd" },
  { symbol: "IDEA", name: "Vodafone Idea Ltd" },
  { symbol: "INDIGO", name: "InterGlobe Aviation Ltd" },
  { symbol: "GAIL", name: "GAIL (India) Ltd" },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd" },
  { symbol: "PETRONET", name: "Petronet LNG Ltd" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International Ltd" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Ltd" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd" },
  { symbol: "PAGEIND", name: "Page Industries Ltd" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks Ltd" },
  { symbol: "COLPAL", name: "Colgate-Palmolive (India) Ltd" },
  { symbol: "VBL", name: "Varun Beverages Ltd" },
  { symbol: "POLYCAB", name: "Polycab India Ltd" },
  { symbol: "HAVELLS", name: "Havells India Ltd" },
  { symbol: "CGPOWER", name: "CG Power and Industrial Solutions Ltd" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd" },
  { symbol: "LTIM", name: "LTIMindtree Ltd" },
  { symbol: "PERSISTENT", name: "Persistent Systems Ltd" },
  { symbol: "MPHASIS", name: "Mphasis Ltd" },
  { symbol: "COFORGE", name: "Coforge Ltd" },
  { symbol: "LTTS", name: "L&T Technology Services Ltd" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings Ltd" },
  { symbol: "KPITTECH", name: "KPIT Technologies Ltd" },
  { symbol: "SRF", name: "SRF Ltd" },
  { symbol: "PIIND", name: "PI Industries Ltd" },
  { symbol: "UPL", name: "UPL Ltd" },
  { symbol: "COROMANDEL", name: "Coromandel International Ltd" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd" },
  { symbol: "TORNTPOWER", name: "Torrent Power Ltd" },
  { symbol: "IGL", name: "Indraprastha Gas Ltd" },
  { symbol: "MGL", name: "Mahanagar Gas Ltd" },
  { symbol: "BERGEPAINT", name: "Berger Paints India Ltd" },
  { symbol: "UBL", name: "United Breweries Ltd" },
  { symbol: "INDHOTEL", name: "The Indian Hotels Company Ltd" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Ltd" },
  { symbol: "LODHA", name: "Macrotech Developers Ltd" },
  { symbol: "DLF", name: "DLF Ltd" },
  { symbol: "GODREJPROP", name: "Godrej Properties Ltd" },
  { symbol: "PHOENIXLTD", name: "The Phoenix Mills Ltd" },
  { symbol: "MINDTREE", name: "Mindtree Ltd" },
  { symbol: "ATUL", name: "Atul Ltd" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International Ltd" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Ltd" }
];

export const stockCountLabel = `${nseStocks.length}+ NSE symbols loaded`;
